### ISSUE TITLE
High Load Plugin

### ISSUE THREAD

**Issue by IlPicasso** [TigerHix/Mine-Fortress#10]
Hello, 

I wanted to run the plugin with 64 players only and it lagged really bad. Wanted to ask for optimizations on the code

Here are the timings

http://www.spigotmc.org/go/timings?url=12827566

**Comment by TigerHix** [comment]
D: No! Never set the maximum player amount beyond 16, which is what they did for Team Fortress 2. 

There is no way to optimize this issue significantly, due to the lags are created by spawning entities (which are the bullets fired by guns). Imagine all your players are firing the 10-snowball-per-shot Scattergun at the same time - the server has to spawn 64*10=640 entities in one tick. That creates lag for any server. Not to mention resource-consuming sentry guns or holograms.

I would still try to do some optimizations as much as I can, but the best way would be setting 64 to 16 and perhaps switch to a powerful single-core server.
